### ISSUE TITLE
Application stuck at "Awaiting events"

### ISSUE THREAD

**Issue by SeraphYears** [Xferno2/PS2RPC#1]
![image](https://user-images.githubusercontent.com/82191365/144155843-dbc00ada-611d-4375-8bf1-e6c6bfa4c091.png)

I have everything set up as intended, I even allowed my PC to share the folder so that it'd recognize my PS2, but it's still stuck here.

**Comment by Xferno2** [comment]
Hover over the question mark it will tell you what you need to know.
Basically don't open a game before running the application, open the app then run the ps2 game. If you are not running a game but still shows up, just try play something from the SMB folder.

**Comment by SeraphYears** [comment]
I tried that with God of War. No result.

Wait, you said SMB folder. There's nothing in there, everything is coming from the USB.

**Comment by Xferno2** [comment]
For this program to work all of the games you want to be shown on discord have to come from the SMB folder otherwise it doesn't work.
